// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqSFiwF1fZyOB_K_om70W5hJvhjE6wHLE',
    appId: '1:171280757727:web:22b2d32f928b8364578a6a',
    messagingSenderId: '171280757727',
    projectId: 'chatapp-759e0',
    authDomain: 'chatapp-759e0.firebaseapp.com',
    databaseURL: 'https://chatapp-759e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-759e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6szKKZE5OQyoEedDx3U0BB_6EVXLpkD4',
    appId: '1:171280757727:android:a4b772acab502ece578a6a',
    messagingSenderId: '171280757727',
    projectId: 'chatapp-759e0',
    databaseURL: 'https://chatapp-759e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-759e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNlkzq_puMEpukzbvRM7cSSRZ9Vr-V2E',
    appId: '1:171280757727:ios:ffb1019bb5669085578a6a',
    messagingSenderId: '171280757727',
    projectId: 'chatapp-759e0',
    databaseURL: 'https://chatapp-759e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-759e0.appspot.com',
    iosBundleId: 'com.example.minimalchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqSFiwF1fZyOB_K_om70W5hJvhjE6wHLE',
    appId: '1:171280757727:web:8898d3adfccba113578a6a',
    messagingSenderId: '171280757727',
    projectId: 'chatapp-759e0',
    authDomain: 'chatapp-759e0.firebaseapp.com',
    databaseURL: 'https://chatapp-759e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-759e0.appspot.com',
  );
}
